"""Write the protocol before fitting or inspecting strategy results."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
ROOT=Path(__file__).resolve().parents[1]
def freeze():
 p=ROOT/'simulation/selector-research/plan.json'
 if p.exists():return
 cfg=dict(version='momentum-selector-v1',createdAt=datetime.now(timezone.utc).isoformat(),evaluationYears=[2024,2025,2026],validation='July–December of the preceding year; each year uses a newly trained frozen model. Evaluation ends 2026-08-31.',trainingWindows=['all','5y','3y'],embargoDays=1,trainOnlyClosedLabels=True,trainingSampling='Two signal opportunities per UTC day per asset; predictions on every completed 4-hour signal.',models={'boost':{'max_iter':100,'max_leaf_nodes':7,'l2_regularization':10,'learning_rate':.05,'min_samples_leaf':60,'early_stopping':False},'mlp':{'hidden_layer_sizes':[32,16,8],'alpha':3,'max_iter':180,'batch_size':128,'early_stopping':False,'random_state':42}},target='Independent candidate net return divided by initial dollar risk budget, using the shared leveraged execution primitives, actual funding and trailing stop. Clip training target to [-3,6]; report unclipped realized account results.',entryThresholdNetR=.10,selection='Pick highest validation return minus maximum drawdown with at least 20 closed trades, separately by model family. Break ties by fixed model/window order. If none eligible, retain baseline; all candidates still reported.',dailyContext='Auxiliary logistic regression for BTC 14-day direction. Coin Metrics daily prices from 2014 for fitting, cutoff strictly before prediction year. Predict normalized daily features from Binance futures history (source transfer); never label 2014 daily prices as leveraged trade outcomes. all/5y/3y apply separately to both context model and available futures labels.',dailyContextAblation='Include boost-all without the auxiliary daily model.',exits=['original 2.5 ATR trailing','fixed 2R target without trailing','4 ATR target with original trailing'],exitSelection='Compare exit variants only on the selector chosen from the prior validation period; do not select a winner from evaluation returns.',costStress='Double fees and slippage, unchanged actual funding.',promotion=False,limitations=['All evaluation years were already examined in prior experiments; exploratory historical comparison, not fresh holdout evidence.','Current BTC/ETH/SOL asset selection; no cross-sectional universe expansion in this first selector experiment.','Overlapping labels are not independent trades; training subsampling reduces but does not eliminate overlap.','Daily context may not improve future returns; no uncalibrated score presented as win probability.'])
 cfg['inputHashes']={str(f):hashlib.sha256(f.read_bytes()).hexdigest() for f in [Path('/tmp/paper-long-cache/market.json'),Path('/tmp/paper-long-cache/manifest.json'),ROOT/'simulation/selector-research/btc-daily.json']}
 p.write_text(json.dumps(cfg,ensure_ascii=False,indent=2))
if __name__=='__main__':freeze()
