'use strict';
const assert=require('node:assert/strict'),P=require('./paper_engine.cjs'),B=require('./build_momentum.cjs');
const start=Date.UTC(2026,0,1),step=900000,rows=Array.from({length:36},(_,i)=>({t:start+i*step,end:start+(i+1)*step-1,open:100,high:101,low:99.5,close:100,volume:1}));
const market={crypto:{BTC:{frames:{'15m':rows},funding:[]}}},q={side:'long',at:rows[15].end,indicatorAt:rows[15].end,price:100,stop:97,target:null,atr:1,rank:1,pattern:'momentum14',reason:'fixture',holdBars:2880,trailLong:97};
const feed=()=>q,observed=start+4*3600000+7*60000;
let a=P.run(P.create('crypto',observed,'momentum14'),market,{mode:'forward',now:observed,provider:feed});
assert.equal(a.positions.length,0);assert.equal(a.pending.length,1);assert.equal(a.pending[0].createdAt,observed);
a=P.run(a,market,{mode:'forward',now:start+5*3600000+7*60000,provider:feed});
assert.equal(a.positions.length,1);assert.equal(a.positions[0].entryAt,start+4*3600000+15*60000);
const repeat=P.run(a,market,{mode:'forward',now:start+5*3600000+7*60000,provider:feed});assert.deepEqual(repeat.events,a.events);
const later=start+8*3600000+7*60000;
rows[31].low=98;rows[32].low=98;rows[33].low=98;
const reverse=()=>({...q,at:rows[31].end,indicatorAt:rows[31].end,side:'short',stop:103,exitLong:true,trailLong:99});
const waiting=P.run(a,market,{mode:'forward',now:later,provider:reverse});
assert.equal(waiting.positions.length,1,'Late observation invented a past exit');
assert.equal(waiting.positions[0].stop,97);assert.equal(waiting.positions[0].pendingStop.price,99);
assert.equal(waiting.positions[0].exitNotBefore,later);
const closed=P.run(waiting,market,{mode:'forward',now:start+8*3600000+37*60000,provider:reverse});
assert.equal(closed.trades[0].exitAt,start+8*3600000+15*60000);assert.equal(closed.trades[0].exitReason,'14일 모멘텀 반전');
const trailFeed=()=>({...q,at:rows[31].end,indicatorAt:rows[31].end,trailLong:99});
const trailing=P.run(a,market,{mode:'forward',now:later,provider:trailFeed});
const stopped=P.run(trailing,market,{mode:'forward',now:start+8*3600000+37*60000,provider:trailFeed});
assert.equal(stopped.trades[0].exitAt,rows[33].end);assert.equal(stopped.trades[0].exitReason,'손절');
// The real provider uses only the latest completed 4h signal, and goes idle at gaps.
const history=Array.from({length:4000},(_,i)=>({...rows[0],t:start+i*step,end:start+(i+1)*step-1,open:100+i*.01,close:100+i*.01,high:101+i*.01,low:99+i*.01}));
const providers=B.providers({crypto:{BTC:{frames:{'15m':history}}}}),end=history.at(-1).end;
const current=providers.forward('BTC',history.slice(-260));assert(current.indicatorAt<=end);assert(end-current.indicatorAt<14400000);
assert.equal(providers.forward('BTC',[{...history.at(-1),end:end+14400000}]).side,null);
console.log('Momentum forward: observed next-bar entry, idempotence, no retroactive exits/stops, and 4h freshness passed');
