'use strict';
const assert=require('node:assert/strict');
const H=require('../assets/market-home.js'),R=require('./build_home_rankings.cjs');
const now=Date.parse('2026-10-03T23:00:00Z');
const a=(symbol,score,code,holding='hold')=>({symbol,score,asOf:'2026-10-02',plan:{code,holding:{code:holding}}});
const inputs={Z:a('Z',100,'watch'),B:a('B',90,'buy'),A:a('A',90,'buy'),C:a('C',80,'buy'),D:a('D',70,'buy'),P:a('P',0,'avoid','protect'),Y:a('Y',2,'avoid','reduce'),X:a('X',2,'avoid','reduce'),S:a('S',5,'confirm','reduce'),N:a('N',null,'buy','reduce')};
assert.deepEqual(R.select(inputs).buy.map(q=>q.symbol),['A','B','C']);
assert.deepEqual(R.select(inputs).sell.map(q=>q.symbol),['X','Y','S']);
assert.equal(R.select({Z:inputs.Z}).buy.length,0);
assert.equal(R.select({B:inputs.B}).buy.length,1);
assert.deepEqual(H.weekBounds(now),{start:'2026-09-28',end:'2026-10-02'});
assert.equal(H.weekBounds(Date.parse('2026-10-05T02:00:00Z')).start,'2026-09-28');
assert.equal(H.weekBounds(Date.parse('2026-10-05T05:00:00Z')).start,'2026-10-05');
const item={importance:'important',sourceStatus:'ready',fromCache:false,publishedAt:'2026-10-03T22:00:00Z',firstPublishedAt:'2026-10-03T22:00:00Z',translationStatus:'ready',headlineKo:'새 발표',summaryKo:'확인된 발표 요약',url:'https://www.federalreserve.gov/newsevents/pressreleases/test.htm'};
assert(H.breaking(item,now));assert(!H.breaking({...item,fromCache:true},now));
assert(!H.breaking({...item,firstPublishedAt:'2026-10-02T22:00:00Z'},now));
assert(!H.breaking(item,now+2*3600000));
assert.equal(H.eligibleNews([{...item,url:'javascript:alert(1)'}],now).length,0);
assert.equal(H.eligibleNews([{...item,publishedAt:'2026-09-01T22:00:00Z'}],now).length,0);
assert.equal(H.rankRows([{symbol:'A',asOf:'2026-09-20'}],now).length,0);
const recap={asOf:'2026-10-02',weekStart:'2026-09-28',sectors:[{symbol:'XLK',name:'기술',icon:'cpu',asOf:'2026-10-02',status:'ready',day:1.3,week:2.8},{symbol:'XLE',name:'에너지',icon:'fuel',asOf:'2026-10-02',status:'ready',day:-1.1,week:-2.2}]};
assert.equal(H.scale(H.chartRows(recap,now)),3.2);
const html=H.chartHtml(recap,now);
assert(html.includes('hp-fall'));assert(html.includes('hp-rise'));assert(html.includes('width:43.74999999999999%')||html.includes('width:43.75%'));
assert(!html.includes('<table'));assert(!html.includes('>+1.30%<'));
const monday=Date.parse('2026-10-05T13:00:00Z');
assert.equal(H.quoteValues(recap.sectors[0],recap,monday).week,null);
assert.equal(H.quoteValues({...recap.sectors[0],asOf:'2026-10-01'},recap,now).day,null);
assert.equal(H.quoteValues(recap.sectors[0],recap,now+7*86400000).day,null);
assert(!/NaN|Infinity/.test(H.chartHtml({asOf:null,sectors:[]},now)));
assert(H.newsHtml({news:[{...item,headlineKo:'<script>alert(1)</script>'}],feeds:[]},now).includes('&lt;script&gt;'));
console.log('Home: shared ranking gates, no padding, Monday-Friday periods, stale dates, breaking expiry, safe summaries and equal chart scales passed.');
