const assert=require('node:assert/strict'),g=require('../assets/learned-guide.js');
const now=Date.parse('2026-09-11T22:00:00Z'),e={symbol:'TEST',price:100,asOf:'2026-09-11'};
const forecast={horizon:126,anchor:100,base:105,bear:90,bull:120,learned:true,logReturn:Math.log(1.05),lowLogReturn:Math.log(.9),highLogReturn:Math.log(1.2)};
const data={status:'trained',generatedAt:'2026-09-11T21:00:00Z',stocks:{TEST:{asOf:e.asOf,price:100,predictions:{126:{status:'eligible',forecast}}}}};
assert(g.inspect(data,e,126,now).eligible);
assert(!g.inspect(data,e,126,now+7*86400000).eligible);
assert(!g.inspect(data,{...e,price:90},126,now).eligible);
assert(!g.inspect(null,e,126,now).eligible);
assert(!g.inspect(data,e,252,now).eligible);
data.stocks.TEST.predictions[126].status='withheld';assert(!g.inspect(data,e,126,now).eligible);
data.stocks.TEST.predictions[126].status='eligible';forecast.base=Infinity;assert(!g.inspect(data,e,126,now).eligible);
console.log('Learned display: eligible, withheld, stale, price mismatch, missing horizon and invalid range guards passed');
const fs=require('node:fs'),ml=JSON.parse(fs.readFileSync('ml/latest.json')),prices=JSON.parse(fs.readFileSync('forecasts/latest.json')),nvda=prices.stocks.NVDA;
const state=g.inspect(ml,nvda,252),raw=ml.stocks.NVDA.predictions[252].forecast;
assert(state.researchForecast);assert.equal(state.researchForecast.base,raw.base);
assert.equal(state.forecast,null,'Failed-grade research must not qualify for ranking/entry');
assert(g.panel(ml,nvda,252).includes('방향 일치 / 항상 상승'));assert(g.panel(ml,nvda,252).includes('검증 미통과'));
const later={...nvda,price:nvda.price*1.3,asOf:'2026-09-12',history:[...nvda.history,{date:'2026-09-12',close:nvda.price*1.3}]};
const old=g.inspect(ml,later,252);assert(old.researchForecast);assert(!old.eligible);
const chart=g.chartEntry(ml,later,252);assert.equal(chart.price,raw.anchor);assert.equal(chart.asOf,ml.stocks.NVDA.asOf);assert(chart.history.every(q=>q.date<=chart.asOf));
assert.equal(g.allPeriods(ml,chart)[252].base,raw.base);
const broken=structuredClone(ml);broken.stocks.NVDA.predictions[252].forecast.base*=2;assert.equal(g.inspect(broken,nvda,252).researchForecast,null);
const leak=structuredClone(ml);leak.stocks.NVDA.predictions[252].training.calibrationTargetThrough='2026-09-12';assert.equal(g.inspect(leak,nvda,252).researchForecast,null);
console.log('NVDA raw research, independent entry grade, original reference, malformed price and training maturity passed');
